# Generated by Django 5.2 on 2025-04-25 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriadopersonalizado',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='feriadopersonalizado',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='feriadopersonalizado',
            name='mes',
        ),
        migrations.AddField(
            model_name='feriadopersonalizado',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='feriadopersonalizado',
            name='tipo',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('estadual', 'Estadual'), ('municipal', 'Municipal'), ('facultativo', 'Ponto Facultativo')], default='data', max_length=20),
        ),
    ]
