# Generated by Django 5.2 on 2025-05-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_alter_feriadopersonalizado_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('data_recebimento', models.DateTimeField()),
                ('respondido', models.BooleanField(default=False)),
            ],
        ),
    ]
