# Generated by Django 5.2 on 2025-04-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='sigla',
        ),
        migrations.RemoveField(
            model_name='feriado',
            name='nome',
        ),
        migrations.AddField(
            model_name='feriado',
            name='descricao',
            field=models.CharField(default='Feriados', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feriado',
            name='estadual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feriado',
            name='municipal',
            field=models.BooleanField(default=False),
        ),
    ]
