# Generated by Django 5.2 on 2025-04-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='feriado',
            name='municipio',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Feriado',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
