# Generated by Django 5.2 on 2025-04-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0005_remove_feriado_estado_remove_municipio_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('estadual', 'Estadual'), ('municipal', 'Municipal'), ('facultativo', 'Ponto Facultativo')], max_length=20)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
