# Generated by Django 5.2 on 2025-04-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_remove_feriadopersonalizado_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriadopersonalizado',
            name='tipo',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('estadual', 'Estadual'), ('municipal', 'Municipal'), ('facultativo', 'Ponto Facultativo')], default='Feriados', max_length=20),
        ),
    ]
