# Generated by Django 5.2 on 2025-04-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_alter_feriadopersonalizado_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriadopersonalizado',
            name='tipo',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('estadual', 'Estadual'), ('municipal', 'Municipal'), ('facultativo', 'Ponto Facultativo')], default='nacional', max_length=20),
        ),
    ]
